spring:
  main:
    banner-mode: console
  profiles:
    active: async
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.56.1\MSSQLSERVER:1433;database=drp;encrypt=true;trustServerCertificate=true;
    username: sa
    password: sqlserver


app:
  file-trigger:
    check-period-sec: 30
  domains:
    -
      name: alj
      dbCron: 0 * * * * ?
  maxCSVContentLines: 1000
  jobid-pattern: yyyyMMddHHmmssSSS
  sftp:
    host: gcc-uat.hostedtax.thomsonreuters.com
    port: 2222
    username: ofv-uat.gcc-uat
    password: siTr8itrtabfejKahkLv5F4mDsnwABx3
    directory:
      outbound: /input
      inbound: output
  path:
    config: config
    job: job
    output: out
    domain:
      config: config/domain
      job:
        dfi-out: dfi_out
        dfi-in: dfi_in
  file:
    dfi-properties: properties.xml
    dfi-properties-map: map.properties

encryptor:
  common:
    pwd: ONESOURCEFVAT

logging:
  config: config/logback_config.xml